const path = require('path');

module.exports = {
  entry: './src/index.ts',
  target: 'node',
  devtool: 'inline-source-map',
  module: {
    rules: [{
        test: /\.ts?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        use: [
          'style-loader',
          {
            loader: "@teamsupercell/typings-for-css-modules-loader",
            options: {
              banner:
                "/** autogenerated by typings-for-css-modules-loader. **/ \n// Please do not change this file!"
            }
          },
          {
            loader: "css-loader",
            options: {
              modules: true
            }
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".css"]
  },
  output: {
    filename: 'leaflet-velocity.js',
    path: path.resolve(__dirname, 'dist')
  }
};
