/** autogenerated by typings-for-css-modules-loader. **/
// Please do not change this file!
declare namespace LeafletVelocityCssNamespace {
  export interface ILeafletVelocityCss {
    leafletControlVelocity: string;
  }
}

declare const LeafletVelocityCssModule: LeafletVelocityCssNamespace.ILeafletVelocityCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LeafletVelocityCssNamespace.ILeafletVelocityCss;
};

export = LeafletVelocityCssModule;
